### ISSUE TITLE
Build project error

### ISSUE THREAD

**Issue by vanquocktcn** [MrCMS/Ecommerce#13]
![2016-08-27_235910](https://cloud.githubusercontent.com/assets/6220768/18028838/5937adec-6cb2-11e6-920e-8d002f054c5a.jpg)

**Comment by NguyenDacMinh** [comment]
Cậu cài bản visual studio 2015 đi thì mới chạy được đoạn code đó!
Đấy là cú pháp mới trong C# .Net 4.6... đấy

**Comment by Will-Bill** [comment]
Make sure you have .NET 4.6 installed.
